language: java
sudo: false
install: true
jdk: oraclejdk7
script: ./travis.sh

env:
  - JOB=WEB UNUSED=000
  - JOB=WEB UNUSED=001
  - JOB=WEB UNUSED=002
  - JOB=WEB UNUSED=003
  - JOB=WEB UNUSED=004
  - JOB=WEB UNUSED=005
  - JOB=WEB UNUSED=006
  - JOB=WEB UNUSED=007
  - JOB=WEB UNUSED=008
  - JOB=WEB UNUSED=009
  - JOB=WEB UNUSED=010
  - JOB=WEB UNUSED=011
  - JOB=WEB UNUSED=012
  - JOB=WEB UNUSED=013
  - JOB=WEB UNUSED=014
  - JOB=WEB UNUSED=015
  - JOB=WEB UNUSED=016
  - JOB=WEB UNUSED=017
  - JOB=WEB UNUSED=018
  - JOB=WEB UNUSED=019
  - JOB=WEB UNUSED=020
  - JOB=WEB UNUSED=021
  - JOB=WEB UNUSED=022
  - JOB=WEB UNUSED=023
  - JOB=WEB UNUSED=024
  - JOB=WEB UNUSED=025
  - JOB=WEB UNUSED=026
  - JOB=WEB UNUSED=027
  - JOB=WEB UNUSED=028
  - JOB=WEB UNUSED=029

matrix:
  fast_finish: true

cache:
  directories:
    - '$HOME/.m2/repository'
    - 'server/sonar-web/node'
    - 'server/sonar-web/node_modules'

before_cache:
  - 'find ~/.m2/repository -type d -name \*-SNAPSHOT -exec rm -rf {} \;'
  - 'find ~/.m2/repository -name maven-metadata-\* -exec rm {} \;'
  - 'find ~/.m2/repository -name resolver-status.properties -exec rm {} \;'

notifications:
  email: false
