language: java
sudo: false
install: true
jdk: oraclejdk7
script: ./travis.sh

env:
  - JOB=WEB UNUSED=000
  - JOB=WEB UNUSED=001
  - JOB=WEB UNUSED=002
  - JOB=WEB UNUSED=003
  - JOB=WEB UNUSED=004
  - JOB=WEB UNUSED=005
  - JOB=WEB UNUSED=006
  - JOB=WEB UNUSED=007
  - JOB=WEB UNUSED=008
  - JOB=WEB UNUSED=009

matrix:
  fast_finish: true

cache:
  directories:
    - '$HOME/.m2/repository'
    - 'server/sonar-web/node'
    - 'server/sonar-web/node_modules'

before_cache:
  - 'find ~/.m2/repository -type d -name \*-SNAPSHOT -exec rm -rf {} \;'
  - 'find ~/.m2/repository -name maven-metadata-\* -exec rm {} \;'
  - 'find ~/.m2/repository -name resolver-status.properties -exec rm {} \;'

notifications:
  email: false
